import Head from 'next/head'
import divide from '../assets/divide.svg'
import equals from '../assets/equals.svg'
import minus from '../assets/minus.svg'
import percent from '../assets/percent.svg'
import plus from '../assets/plus.svg'
import plusminus from '../assets/plusminus.svg'
import result from '../assets/result.svg'
import x from '../assets/x.svg'
import Image from 'next/image'
import { NumberButton } from '@/components/NumberButton'
import { OperatorButton } from '@/components/OperatorButton'

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="calculator">
          <div id="display">
            <div id="last-calc">1 + 1</div>
            <div id="result">
              <Image src={equals} alt="sinal de igual" />
              <span>2</span>
            </div>
          </div>
          <div id="keyboard">
            <NumberButton value={"CE"} secondary />
            <NumberButton value={'C'} />
            <OperatorButton type={percent} primary />
            <OperatorButton type={divide} />
            <NumberButton value={7} />
            <NumberButton value={8} />
            <NumberButton value={9} />
            <OperatorButton type={x} />
            <NumberButton value={4} />
            <NumberButton value={5} />
            <NumberButton value={6} />
            <OperatorButton type={minus} />
            <NumberButton value={1} />
            <NumberButton value={2} />
            <NumberButton value={3} />
            <OperatorButton type={plus} />
            <OperatorButton type={plusminus} primary />
            <NumberButton value={0} />
            <NumberButton value={','} />
            <OperatorButton type={result} quartiary />
          </div>
        </div>
      </main>
    </>
  )
}
