import Head from 'next/head'
import divide from '../assets/divide.svg'
import equals from '../assets/equals.svg'
import minus from '../assets/minus.svg'
import percent from '../assets/percent.svg'
import plus from '../assets/plus.svg'
import plusminus from '../assets/plusminus.svg'
import result from '../assets/result.svg'
import x from '../assets/x.svg'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="calculator">
          <div id="display">
            <div id="last-calc">1 + 1</div>
            <div id="result">
              <Image src={equals} alt="sinal de igual" />
              <span>2</span>
            </div>
          </div>
          <div id="keyboard">
            <button className="secondary">CE</button>
            <button>C</button>
            <button>
              <Image src={percent} alt="Percent" />
            </button>
            <button className="tertiary">
              <Image src={divide} alt="Divide" />
            </button>
            <button>7</button>
            <button>8</button>
            <button>9</button>
            <button className="tertiary">
              <Image src={x} alt="Multiplication" />
            </button>
            <button>4</button>
            <button>5</button>
            <button>6</button>
            <button className="tertiary">
              <Image src={minus} alt="Minus" />
            </button>
            <button>1</button>
            <button>2</button>
            <button>3</button>
            <button className="tertiary">
              <Image src={plus} alt="Plus" />
            </button>
            <button>
              <Image src={plusminus} alt="PlusMinus" />
            </button>
            <button>0</button>
            <button>,</button>
            <button className="quartiary">
              <Image src={result} alt="Equals" />
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
